//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApotekOnlineDBLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class DaftarObat
    {
        public int ObatID { get; set; }
        public string NamaObat { get; set; }
        public string Keterangan { get; set; }
        public double Harga { get; set; }
        public Nullable<int> Stok { get; set; }
    }
}
