//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApotekOnlineDBLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hendra
    {
        public int PasienID { get; set; }
        public string NamaPasien { get; set; }
        public string Keluhan { get; set; }
        public Nullable<System.DateTime> Tanggal { get; set; }
    }
}
